apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets
  - mariadb.yaml
  - photoprism.yaml
  - ingress.yaml

configMapGenerator:
  - name: mariadb-config
    namespace: app-photoprism
    envs:
      - config/mariadb.env

  - name: photoprism-config
    namespace: app-photoprism
    envs:
      - config/photoprism.env
