---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: photoprism-oidc-secrets
  namespace: app-photoprism
spec:
  encryptedData:
    PHOTOPRISM_OIDC_SECRET: AgBmHpXfUPLwF/X/+XtFzmNxKJOzD2fjc9JrmZKxEYHKraN1w3o4zrsJTwvMQ5Jkmm1H0YV8c1Ie3KVFP/tx49a/kx866k0vnV9YepiD0IHlV8eeTTB+sqCNYBvKCtMugB7EntZoL6UhQzbfWXOmUOui/ZmuGFW4q05tZdubAPB3cJyM61LtpzYweEKdDoBvOIifPUdwwVZgJMreH21NrTHsWDEnAReuGCNBwQr2t2dHkVZb3Th/Efi3DdyPHf/Nl9x2npPjSe8FJp/JJ7qp3jbcTSJjn9yhq7zeW/sJLqtUleIHHvIeOhA3d1DARs6hP6PfShryCGRS9ccmWWJQvSsswnRgDa03vV9jgaVmysRXI7zPv3FqjlFO3IrwgXbY8Gx4s0XX4WVKGo5subWgOnMFOP6Jkd/lV4U84stO9Ze60GyktyNcz1mRQBOI0GIxLc6J+Ur1cOEkjAtUUox5Z7ipHZEG82ZhMDV+20ZoqwbX7nicbCHibsvjpFrz0sB86JeHAXW5C4MDidshpm+TOTDi1LTYh+zf0iPfxrCA8ZQn9eCo+xk4Bk3ce8h7hCE7l8iUoSViLl87BSeoGgDQmwKybIZ1Xo4olBY+lN2Sooz1OBsSFr+FoLbvx00Lc99/405f48lcuhOdic76WDgeeYmfIl2POVKw+anFqOWm1qeVh0JCYGZ+ZaEo/Q55RB6ppLQroCG/S59UuM7Kun0AC9NR+SKVz3aHlbwfcvC2I4niBY7QX1mxEUP+QEIQNgA8m1Ong9C+4h1k01dVHloBNvUT1UkjTqv/ELk=
  template:
    metadata:
      name: photoprism-oidc-secrets
      namespace: app-photoprism
    type: Opaque
