apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rtorrent-flood.yaml
configMapGenerator:
  - name: rtorrent-flood-config
    namespace: app-servarr
    envs:
      - config/rtorrent-flood.env
  - name: rtorrent-rc
    namespace: app-servarr
    files:
      - config/rtorrent.rc
