apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fallback.yaml

configMapGenerator:
  - name: fallback-config
    namespace: app-minecraft
    envs:
      - config/fallback.env
