apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - survival.yaml

configMapGenerator:
  - name: spectrum-config
    namespace: app-minecraft
    envs:
      - config/survival.env
