---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc-secrets
  namespace: app-paperless-ngx
spec:
  encryptedData:
    client-secret: AgBKzp48jveOHq07pWbkLp0R2YWh8ZzLU5lhseuVwGcrK2+7ollwqewGGqh8UrDcGZQ5+AH1ixVzQsaAT6qV0shMggLprgDj+Qb4+QUFmJMDveYnaHZ5EGXdNBChv3WNuGMuQ+C1yFxZjLQORQoR7yVclIkRMldQ7zz9kdvqVs1lmthf6/gxesJAZjm3ETGt/jHRCj+g/l8kH/wVHW01DTszRRMGCWRhtxKsRadKLCp5oTl5AsmKqvnkxdqK1/WCaxlVGdULhU4+Fo8eANbNgeTRVVSLR7KeVZsXVCkzfaQyjWEAwm0BTw02tNaqqCzV31Q/+z8cfVObKj8s0yymgsHKeDrV1z2gBlxAjzvydrp2VfxI6P8HZIpvCytHRntVKJinPGCmoPM2G3c+n2W/SddAIasOu987p3ie7NoKQ4U9dgMCH6CaJNjzDfbXX6IDquEKCeHJ6Tzqe9C8oV5B0p7O2lFjoRrlvjBGswdVy9B/iTPWRffnxBOcMR2/ylX0Gp6MayuYIY1ts5cJHdH6IypcK5I1s7NCSCS7ySAbQbkHYkeckyunSDlLxRVHfja7cNob79WTdZLiSQTX+08ZtC/Y5sJaJFjGDesMOjZaVA3SVR+o7FR9CRBNcsWpb4vLO1Uen772E/kD2O87A5Unc0yldoeu+sqrzQNcmBGjAFeRjG8LFL6edwh5IHvxk6+AF8wwdW9Ituazt1wWo1K2XseZqJ5st4CpbSwsUt2vmlZpXws4znz6T75msPtWf7ddWLafjoP9bls0ZaF9FhWwkzoGTVQBLerNg1w=
  template:
    metadata:
      name: paperless-oidc-secrets
      namespace: app-paperless-ngx
    type: Opaque
