apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: app-n8n
spec:
  forwardAuth:
    address: http://authelia.app-authelia.svc:9091/api/authz/forward-auth?authelia_url=https://auth.cluster.arpa
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: app-n8n

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`n8n.cluster.arpa`)
      kind: Rule
      middlewares:
        - name: authelia-forwardauth
          namespace: app-n8n
      services:
        - name: n8n
          namespace: app-n8n
          port: 5678
  tls:
    secretName: traefik-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: app-n8n
spec:
  secretName: traefik-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "n8n.cluster.arpa"
  dnsNames:
    - "n8n.cluster.arpa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-n8n

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
