apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets
  - config.yaml
  - cnpg.yaml
  - n8n.yaml
  - ingressroute.yaml
configMapGenerator:
  - name: n8n-hooks
    namespace: app-n8n
    files:
      - hooks.js
