apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: app-n8n
spec:
  selector:
    app: n8n
  ports:
    - protocol: TCP
      name: http
      port: 5678
      targetPort: 5678
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: app-n8n
spec:
  selector:
    matchLabels:
      app: n8n
  serviceName: n8n
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:stable
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: n8n-config
            - secretRef:
                name: n8n-secrets
          env:
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-db-app
                  key: host
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-db-app
                  key: port
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-db-app
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-app
                  key: password
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-db-app
                  key: dbname
          ports:
            - containerPort: 5678
              name: http
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-data
            - mountPath: /hooks
              name: n8n-hooks
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: n8n-data
          emptyDir: {}
        - name: n8n-hooks
          configMap:
            name: n8n-hooks
