apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-cluster.yaml
  - secrets
  - redis.yaml
  - synapse.yaml
  - workers

  - ingress.yaml
  - janitor

configMapGenerator:
  - name: synapse-config
    namespace: app-matrix
    files:
      - config/homeserver.yaml
      - config/log.config
