apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-turn-secrets.yaml

  - synapse
  - synapse-admin
  - jitsi
  - element
  - well-known
  - livekit
  - meowlnir
  - mautrix-discord
  - mas
  - integrations-synapse

commonLabels:
  app.kubernetes.io/part-of: matrix-stack
