---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supernote-secrets
  namespace: app-supernote
spec:
  encryptedData:
    jwt-secret: AgAVEvtzFYpB9yOkJ3f1IbgqZkeFDmIeiRVKo+yDx9eHSNhQx2wPodUzvsKtVpgGn9YgiNmFKYqkLDovQcTWXypzvO8AQh4FMvVvXs/NPIfob+Mf/8kNmXfVnwSKPxYakOnWJWrGdwiBVmqdWLd0zfcUl3HtYyW+2KdVcaxEBC/9QIVJyMiW8aLhVfSwSxLQ/z4pL/BDgRgi0F7rI6hSuUA4fmuBY80ytnRhLm79yosqj4jGX8NJZvxqmPDM9T5gKeWVYC0GY99jZZHUoP5BtjhJ7tmm73uiYEbSyerwpJSF968XIbH/YPYdEtrKR/VsClECQe0eI5zXwzgGQzspw2bUk4WWcGRUkaZzA0LCMTBdbQKdWQexmmv7fL0vMVeJrqfYZFTgFj+d/XdSUOeh4xT5TznJb2LbxIGr11nVWpjzNNMKhWnEHHkL85DVYfJ/LI6sg5k/JWRulzgsh25TDrwMsDRHIkFf7c1ZOgJ/ywG44PNKR/s+deq2BVQfY8qJxsfFZaMVZ5kcPTpXpDFtYYmk4K0B6VmTHZwMPzEmafZA9fV83S/0hR5wZa/yNEzHYx3gPttQHs1uI3+yuJNg9/7O2+V65jtHzp5xaUKZk6gbE66DVurqjXSROMT83/71xqQxy9OqDg8t3tpwlrLID1r33jGVK9pQHVYP4nTghO39jUYF6BmRBk68AZ0Fcft/e1VXuHgvnGsWg6A3ULu/fRVfm/w04FFKMwFkvYGCQNbkE7lIAzWUWDOiAPp3i8hdKoLy26hHZKeJWmpzF23+XiyI
  template:
    metadata:
      name: supernote-secrets
      namespace: app-supernote
    type: Opaque
