---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supernote-redis-secrets
  namespace: app-supernote
spec:
  encryptedData:
    REDIS_PASSWORD: AgAMHkF0P3bt+RQjW0iHYi4xoVdX8fJ3aKylSN6SlgJYVTpoTgBLJz3KDoSdEtfItnUGpVT3VG/ANObPMvkxJu1cC2AaOsgH7KQ6pACeCNAeE/AAzhY1eKU+EhvkPiHZVGKmWrkaSmGjHDrxsjfYRHsonSnRqojY+tkfOTAijP4NpXZHt1nOZu01jI1Vs8QndFX0ZbbUNNKYi4eLqkjxJUAjifAgBXg1a3uJLSMAemnjNEemjcW3+R55Vc9X9Sa+1wCDeZzLoYmEOoB+RCiq+3L1Vun0QWaWXITmtNt4BmrUgeBpAbeZYyNucxl7JSzsbjvGNC7gr3+msA++D05me0nDLY4C2AG3JOQsITnYKWkSz/060aCO0Xs3pypYWiYXiipfkvk1flRSHVn2YZ31/SP5DfYe3gDJfL3q/G/Zgr+S1zx2fJ3G/usDYYLHHtMtxBqAZWUCtph5Oz4iu/hSuKScuwgOa4MhBnXKumwfHG0OX413hHO1ntgwkA8tOjwsp4x0V7KSS6RrLmEsuiy55jJlsW4Kjc4GIVfxrdEMYwTFpwB4C81YEkL1pOymOm/lJTOK98jyd/1rdO6L4kxP08RpJL9xG6geqvBqd0UpqRI16739YX0kuy2ou4zvaymlurbEEpgNSIC6z3x0hCfjms2kJhodi1S6mFc1/vN6RBgAoJ1QaS1KFfPLYZw6//nAvTOA5iESdvsDaVFPvaWen5FEsoNkriasHezCRGn0NQ1kSA==
  template:
    metadata:
      name: supernote-redis-secrets
      namespace: app-supernote
    type: Opaque
