---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supernote-secrets
  namespace: app-supernote
spec:
  encryptedData:
    jwt-secret: AgAwAZ2tTvjWuwEyaveLf1QM1V6/+UIiRrsw8fB98k4Z0GTlzzDM/NjQHgFkiVjsv64bMziK6btXURy/BWizw4Ey8gbU4ouRMXPMTcAch2Q7H3uM3CAwPfRD7VkGcXgIxccepaQukYhHBEm1iNe7Gd+NbGMJ/rLGKF+YXj54nUKRzV4NK+cYzYH10gA9D8rLLkvM3iXr6gpc6Oyw5F80GKSGGX5kAEfEgfAaDrM3Z0g4LPyL7z+cisLVUAS+52ML8/OLiOyoi/Qa1BLwTDcka0sj/BGWEbNFSjvz4G4OOEvLZ9/KoerJyD4zEPDcZl6sTqP6jypos0HxvPo7pHYXqf1c11muuf9q+glOl6SEvpPQfalgdZKUAJzPOeZfjZu3qgt5sJFij0tneEgNG42jQipmrZ/03NMoTAxGFBsGy+3bkmBUNCsT9+sPdetpanhMQqqQl3xAE39ZY/MHbG14n4d/do2fna/oeH/iRF/X8n/TQWBGOciWdHF7nwaHA9ek5PBkEebSboT1C2Ox12sNWHppWyIf03YerJxBBNeDDmv7xWP6fHz1C5nljtrR8yUNAc76fDGo73AV9oqrhvkjXCani5vgdsMXdpJTzK5fxLfc+zcFn92PtaHFo/V8H5Fynz2pNnG53Vg8eYj9gHD1vIhsMrWXBwG0MvqwhIW7YCOti9IZFOJ1A+Ho7b0mU7Ru4y7IryYvP1XtWJIH/MpS9ZyIPlDzF+sYUGk/0Yiriqh6lmrMuQqKlP9/mBEAtjBHJ9YbCpDwBDdxygNyRASRK5sE
  template:
    metadata:
      name: supernote-secrets
      namespace: app-supernote
    type: Opaque
