apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-s3-secrets.yaml
  - sealed-coordinator-config.yaml
  - sealed-consensusnode-config.yaml
  - sealed-syncnode-config.yaml
  - sealed-client-config.yaml
  - sealed-filenode-config.yaml
