---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anytype-secrets
  namespace: app-anytype
spec:
  encryptedData:
    ANYTYPE_ACCOUNT_ID: AgCJxCPF3Pqpj4DeVbkG0M7eT0ptIZGTM9hDYOmfxivZ/zX4mb4suP8ss40kmr1p/kKyP3GuuhTAiQl7ByzpdAtFu17iQ2OR5Qg4Dr4cInAiCrxjBlGbMcCHKywLeQQbjgEBJ/CseSvxC2kRclEFDX+8xOpKocQF7Md64kydDqI07gQq+lBGxaRShpcjaBl+vUtpmBu+7NwdXDyZMbgumhG6hUsCa5L4RyOAMkYu6JieHefJ5hm4+x0bdt1DHiONzaLl1e2WlgkF0FhuF0H0N4WGZ5WsKbAr26aFocJ1PAn0PWzLdoYuDiE9ovOP/ifAT4zikz9ffsb55AR1OZ+hVmT95pTgO5p0dCm25exV3XMU62gXf4xdAQa6Oero9t/wtJTQkcqKDQc3SxbHOvwdVvsxa8t4Y471EqWgTxF31wwROi/vOaOjkjq2ZR3GEvZm+lrORhkIcFuzJcU/mS/uX3km10fyoQuUAwCPSJ41Khg/PVEdmubsYNmaoTXnq6WOVY/b6/MlcIVNnHup2IhSLTVnNslB/p9vw76mWsciEGnkF0mRiCbfX5eFzM3BGO0KjSUt930eWkQ1lIssdPV7nKEeFRU+Yp7zf7TAECH1euBsuEjNPWIdQgejdg5yX5bnIoKXY6crC00mexe9XXqIXbqwK/jeXTbhxlOMLLzIpP/t660GqC70GFnlZ+GYHkEXktjt+RKFbFujhzCFGYak1JhMq4j55hq4dnUcduhNiZpJ62F666FpxgiGKV4l6yyYJ98=
    ANYTYPE_ACCOUNT_KEY: AgCOlzfITMaG/+EdbIcfNA78jW4+wi5zsB+NZH5nq02AirwcmWFeIJF0LIqeTEYu/proLB4pmpg4qidGAFfEKl2SooQR/ZRlgXew6SAlN/bm3U/8IGMO2jhZhCMEzmSl994n/V17LtBb2E0NM216S2s/dIQ81YSJ4Pf3ibcrKuJEvm8qw+mjVP6wE33lDzqj+vs8Ch1kpOBrFu25uBVrkhT2W2ZiqjWr2EPk+iNMMG0wDSfZXWg1dKrqANsYYB+aAgW5xQuTFadMz567NIHzx74pfbPJsyVX/Qx+84HluQzYae0kbC+JN08c7Hh0B4NNOfi5IBD36zJL7WcWDuamlb9Bb6p+sDX84H8oQD/oSHGoqrhHZHyEBQNalLvm/9v702H9zAsrnpNmAdit8k6NkCXL7OSAasWRVy5eofHIOAknAy2zMjzHCnxK8KC4Qn22+H4tC7fgtGCDk0iW7nnteAiPxGRzV0GSHDsfOyF1tC/Vq/BjdZ22hTO1p/Ld3oOkKQJOfQNE3VP1jWEdq43SSwJkj/uGn1yy5ScUbHmvRs0VB8Bb/NAI3CtFT40YcGwWMuZaBik52vqwWR89hAaBuOCT/dOHA1cuYELkuUT+Pkx9EUSK6l8o6pMCfFiupMlT52E+z18mrLyScaWgUPQflpF2cC873ZE3NrW/qpaD4YyrnzwgHUhAVhLarogWfVatEez2+dNOgMBfwALK/QJm6b5zvpLAyTCb1iYePwEaGpF1LQ7MsB8f1JVEY0mGx5qQRYIg/Lm6kC0HjjCn6FCJ/cUCNq79qWht0ag/QedprKcjmks3F6JecV4l
  template:
    metadata:
      name: anytype-secrets
      namespace: app-anytype
    type: Opaque
