---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anytype-secrets
  namespace: app-anytype
spec:
  encryptedData:
    ANYTYPE_ACCOUNT_KEY: AgAKW0G7rCH7qfxGDzOvXwZJjsVM78W89OZcHYkQC65zlTuSGfg46H8vAvhsBCJbxVJFXNWNRAbK4qBdbVlMmmHtsaF7MoSxZ4Zk5ZCJXkW2n4mBkQsXnuMQI/SZw1sF/JXfoGWdTG2yPihX/nGd3i41j90EtarLQ0oCnZmQzPS+meOMinjkpjulsFm3UEjKvGpn35FqGvMKaFY267z58YcsM137ETjIh/9aQQ165cwv8qTm0pIYYd+xK7sDcSgL1xldLlbk+62kuaDF18JER8xHZl1Dl8o4DHm9CyNg9fFi/dpzxw9Yotj7qQY5cX7zWZsl9vPE/Mwi+93L4y7qHAFUYwizDLiL8Ipt8VAmcc/10rDPwqUdHLy20mKPSn3oPNJ7qHClx66SQczTKmY3ovkI9kNcfJ5xTKodav1fhW9PMpwkwF09GOr9DOwpXQrP0BGaBmsiLbeKkFkKBY2AxOVPWkAz4ffhZqa4oU0dF140Fj8bSJMl3wMnZoey8el5nU+dYFMfjilfujtaisAj+hwQ4bjrgakDRqayd8LORRMO2iufE7nfZT3pmNSe8IXClEZlklg2TrVCXAl1wDyOXo8CFjSMkMv/CNJbG12MGUBf03hPdM/mqCWigHhPhVwdOvG5vvIM7DOaEj25reXN0JRnrp0X/9h2AM7csyMtE9Yci/l5/BENIlge1iaZXiYZF5erfyQ93n8NFnwKgmaB00mz8uEA/8lBZlMIuVlWuEVQ6xtbTj1t7U7MFwimi6jvkqZbMLFHum7y9IFmFrhR1pqFT7kjgv5RBZufj0vg28eXQuNfrZlpJnhW
  template:
    metadata:
      name: anytype-secrets
      namespace: app-anytype
    type: Opaque
