---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anytype-redis-secrets
  namespace: app-anytype
spec:
  encryptedData:
    password: AgBL+cRmjqjEyalemQezEhx9n6vrO2r1+SZA8dUhVvK2gixyw8Y45mvtnKzQ7Npk+Tm7QFRtImWV0hsq6leBVGEeXXB8HqzWgn0CggUN1kbBrwPVQO4Ra2OedHkT162iPjxzMKMqYOFSrjZg9Q0WR9RggCNZa80NWOn+CRnWZJRgyj1Jd0IdapDqGWQZSk/3zzzG+WBKY917qeNXfY4PSx2wolZ6o0tINSZeuE/eYdYtwxcjhpFhkYnSYsoZfnXcqS1yHXZw/cNkJLzeJn0PS3nKCC5AvDjzXM9z14cjEi1wJ7RefdTjIdZMNKsp0dY20/P4N3wO4kYHY/gGh255FUtygFX/LJY2VnD9B1XdIgJN/ypNg/dnDPhDo3OrGg9AvKfrTaTCT6fXechxIOqZ9SUKJTx/BEwUO6kRmyVoDx6R2abXUgInfuotTR/y1MeZIc9AgXuydndX7T4airMfQ1gyDUPUfMV4IcBeIu4amZmoTVHHh+82Rmhf1REFRibX0DcfVy2b2DPStdbCI0yRRCN+Tlh4nthBy4Tx2aO4WsXTYx9JDlPyiuIpFyob0OYNn+SgvHpFXcpJINVn/LSPzX08qvIfxiLXDXh5E4284m5R4YESiN6EcnP2iuSga98HxXNcX2/Lc+xeepeL6wjMhYeSySfhtQJ2Sj7WpFeu+GhC/vmPtdGHsDeQHp84I0zbLV+UZevqPWBqrvrJ9gQi4Dk6pSs23W+arbieexOIOpwRufclKYpPsgzRxNaBoLGPT2cDUNfSWLnpa7B95JXgKSjQ
  template:
    metadata:
      name: anytype-redis-secrets
      namespace: app-anytype
    type: Opaque
