apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ntfy.yaml
  - ingress.yaml
configMapGenerator:
  - name: ntfy-config
    namespace: app-ntfy
    files:
      - config/server.yml
