apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets
  - openclaw.yaml
  - ingress.yaml

configMapGenerator:
  - name: openclaw-config
    namespace: app-openclaw
    files:
      - openclaw.json=config/openclaw.json
