apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - checkrr.yaml

configMapGenerator:
  - name: checkrr-config
    namespace: app-servarr
    files:
      - config/checkrr.yaml
