---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: app-n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAbGV+3G71kquruE+ryUGtJveGvh8QHDt30/f7tQajR1QliOa4x82/9TfZiZb0aEvyJXeSm3u1VjD0W+6C/fQw1BbdIGKzAY7LqrnIThuC5S57uvJ1/gWt3Y1I8orybG5dE1Rb5HI6LifnqBEowzmWg3nZaSdT7bqG5eRhj5INNCWKg9Cn9YtNiHeZmn6PS/73BWTmC2Cnk0GKfqIoEyEKDcOSKsiWZK52l9foF5PSnKJqLQBKGzZLUrw7QdEnPjhxuVm+OxnAcCkh2+4oNPUXRiyGjzLK6RUKaoA/Th/Aws5E63bfAJgLvG+biG6t6eTudYl89L9Rb0v2fPiKrVruPdotVKRNJ+HSgXBkyz4RTdA2rGGdjcxRszqUzulMR9oYsGzHI52OkQYou+CCuCxWNWbQdX8RKFIrqKI+EEznMm0iEQhXUll50hImWTxaYnmTdLTVKb8Exlskp4w2psbY5l+Bh31SugPEb2fDQc3Tip2mR2evyRmhF1lSGvBghsp+DvMaGaW/cFhxXouQfqeSR6zrqrCAX5+jAolfXBt6uO2rop4/4pJWMvpOJ+fKLMBoncBiGfU20JYQdJod5MFFfiDL8auPkL5qWjWvgcb98VIuqn0nZ4v4Iq2auOCKXjx4ITBW87BxftwNidD8g4qLSj7Uav9EIBCQc2OKiqUmjf4Mu8Ub7tqV+FSWueaP/nis5/TY4E7ulaYkEpl1gFVXVKfy7lUqEE/0eAU42o6rvARnTZlUOeXHt6Zdj0MPuXRoq77ZsncwXJ4VUZBpzU3x+
    N8N_USER_MANAGEMENT_JWT_SECRET: AgA1Wp/1LqMGeDBXaS50MDQk3JFn8FpGjhn0TjbbvMjymRUciYpphxyO3rsfQPUCLVSsfPtVYzp3Ol3or1tOb6mr46ap9Xu3fJ4WnxLo9KVtGYWPjufUUDiphXvWM2doCDok2WDQ98pSkWIHosI/s5jHrajXHrHu4AeOALQUdLMEpk8/pNas3Yw0qsT6zLviyVqMrhbYJ8zvs2hE8XJYMIjfB2wUqLeOZXcHP70GErCnvn5i204h1byreWu6MgFCU6L+R7yPMupisPx7+WxbIdVcjjmXB6f19kS4G64grU6/6G0IpTgoYJCwVIgm8ZcwiwZ3oJMTq2zk6Fv81/EJTNRNW0/UyZeyu0M/mBy9huiKxEi15G5skDpyv6yswLAK6uH3SqXEiFgZU1bzrnsEvTXE3VpwNWNut5kgSISoUmoy7v8eVbAe+S8ZYBI759ha2PVW2wkBr1eNS9k001IWII7MFdmRZwWbt+zBxb9PI6AHCAZHbZt510zVsS9s9HO4SU2JoJj/TdpqzCXAe/kQLqnU3EcvlE6vJkPN0PIEzq/jhPPBCGQ7S0UE+Pusz0Ab3UVZl0LRmqa7WdrNGEdBv+J3Zfl5ZJYecO5UcJoNjfnbdaEq0c+APmVsvcGpDo3twdGmbqRdBfmA0I4mwX/AnbSAE5x4RG9Rwm0Rk6g2FtmFaStvKzBFwtRIu7KJ3Esa/DRUdhw09O3htPWsdXiOwR5mNmTp5ohLGpN/HpE/Gt5WXk2gYiI1ETRZU7/tzCOeGlKIOr7qIvLGNg233G2/qZIg
  template:
    metadata:
      name: n8n-secrets
      namespace: app-n8n
    type: Opaque
