identity_providers:
  oidc:
    clients:
      - client_id: jellyfin
        client_name: Jellyfin
        public: false
        client_secret: {{ secret "/secrets/authelia-client-jellyfin/client-secret" | msquote }}
        authorization_policy: one_factor
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris:
          - https://jellyfin.cluster.arpa/sso/OID/redirect/authelia
          - http://jellyfin.cluster.arpa/sso/OID/redirect/authelia
        scopes:
          - openid
          - profile
          - groups
          - email
        response_types:
          - code
        grant_types:
          - authorization_code
        token_endpoint_auth_method: client_secret_post

      - client_id: matrix-authentication-service
        client_name: Matrix Authentication Service
        public: false
        client_secret: {{ secret "/secrets/authelia-client-mas/client-secret" | msquote }}
        authorization_policy: two_factor
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - https://matrix-auth.borooka.ee/upstream/callback/01HWCM3Q7K8YDNP9Q2X5V1W2Z3
        scopes:
          - openid
          - profile
          - email
        response_types:
          - code
        grant_types:
          - authorization_code
          - refresh_token
        token_endpoint_auth_method: client_secret_basic

      - client_id: photoprism
        client_name: Photoprism
        public: false
        client_secret: {{ secret "/secrets/authelia-client-photoprism/client-secret" | msquote }}
        authorization_policy: two_factor
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - https://photoprism.cluster.arpa/api/v1/oidc/redirect
        scopes:
          - openid
          - profile
          - email
          - address
        response_types:
          - code
        grant_types:
          - authorization_code
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_basic

      - client_id: paperless-ngx
        client_name: Paperless-ngx
        public: false
        client_secret: {{ secret "/secrets/authelia-client-paperless-ngx/client-secret" | msquote }}
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris:
          - https://paperless-ngx.cluster.arpa/accounts/oidc/authelia/login/callback/
        scopes:
          - openid
          - profile
          - email
        response_types:
          - code
        grant_types:
          - authorization_code
        token_endpoint_auth_method: client_secret_basic

      - client_id: peertube
        client_name: PeerTube
        public: false
        client_secret: {{ secret "/secrets/authelia-client-peertube/client-secret" | msquote }}
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris:
          - https://tube.decentm.com/plugins/auth-openid-connect/callback
        scopes:
          - openid
          - profile
          - email
        response_types:
          - code
        grant_types:
          - authorization_code
        token_endpoint_auth_method: client_secret_basic
