apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: app-servarr
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: recyclarr
        spec:
          nodeSelector:
            kubernetes.io/hostname: cadance
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:8.6.0
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
                - sync
              env:
                - name: TZ
                  value: Europe/Tallinn
                - name: LOCALDOMAIN
                  value: cluster.local # Fix c-ares DNS resolution with ndots:5
                - name: RECYCLARR_DATA_DIR
                  value: /data
                - name: SERVARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: servarr-api-key
                      key: value
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
                - name: data
                  mountPath: /data
          volumes:
            - name: config
              configMap:
                name: recyclarr-config
            - name: data
              persistentVolumeClaim:
                claimName: recyclarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-data
  namespace: app-servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-local
