apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingressroutes.yaml
  - themepark-middlewares.yaml
  - secrets
  - sonarr
  - rtorrent-flood
  - prowlarr
  - flaresolverr
  - recyclarr
  - checkrr
  - radarr
  - bazarr
