apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sonarr-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: sonarr
      theme: overseerr
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: radarr-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: radarr
      theme: overseerr
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prowlarr-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: prowlarr
      theme: overseerr
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: qbittorrent-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: qbittorrent
      theme: overseerr
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: qbittorrent-strip-csp
  namespace: app-servarr
spec:
  headers:
    customResponseHeaders:
      content-security-policy: ""
      x-webkit-csp: ""
      X-Frame-Options: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: flood-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: flood
      theme: overseerr
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: flood-strip-csp
  namespace: app-servarr
spec:
  headers:
    customResponseHeaders:
      content-security-policy: ""
      x-webkit-csp: ""
      X-Frame-Options: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bazarr-themepark
  namespace: app-servarr
  labels:
    themepark.dev/managed: "true"
spec:
  plugin:
    themepark:
      app: bazarr
      theme: overseerr
