---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integrations-synapse-janitor
  namespace: app-matrix
  labels:
    app.kubernetes.io/name: integrations-synapse
    app.kubernetes.io/component: janitor
    app.kubernetes.io/part-of: matrix
