apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-nutritrace
resources:
  - sealed-secrets.yaml
  - sealed-oidc-secrets.yaml
  - sealed-ai-secrets.yaml
  - sealed-smtp-secrets.yaml
