---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nutritrace-secrets
  namespace: app-nutritrace
spec:
  encryptedData:
    JWT_SECRET: AgCKToTiWLqX4UYPd9+HDBvIEnqld5hYduSe4BNfJaHozF6j5gvhNQRw28Vdqqcj1NZo5OjeXuiCrPzuVkXUpjDpemSk8e0kbEXKcRxDY7SxatWuhm9+l0Wh93GcMod0BYrzs4ySTtqCYJQ6QIeRBFFdVHZgtXiMqFMTC6BfRSzYwfDAtIAxYy4Kyh4t7v4eXozyqyr8znqycYNJWJygPMF82lelDigD+SdxjEDJuhehEEds+YI083cEZw/rgyO4drcUxEaquNRkIneIANuSzkdMXXuoNAQzYeRorxkPT7l0CK7xvmjpGTFy71pHojLfsegFcM1L0mrrEMRzs7rlwC5aveYSbMvudF2SfrB0xGHU6/TAMjYkGYpHPzKQSHL/78OK8wY9kHb4hiY2QaJ4/w3Ah24bvKI32dJOljrVEWqa0OPstbJBZ+ofICthtNZIt577sU3UNcxPJraNDtj60gmtS9HIo1LIFEfD7o4BOUaRms4GFUzp22jH24rWkuN6wedo/SYnj93hCUdhiGO3zk7ZiD2iGc0z648CMXWPZTgWHi9WKX07jnVddade84RfZmUnfybLP7gtuQVqi53Tef1Mza7zxnwJ0ObYhunWKT1TFsReYdvQlXnDvkIZ1zPTkqpoEloFUjVG8HOzDn7iKaUUNimt/XfyxOU+kwzmUKHvxR9DrtYU28SPdg1LlGGwMSZuaQ6gM2QuvfOI2HPaTOrMIi/bj461XT9r0tX3EKgQw2NpsLihGN+0VLTHAQd1j9H9FJs4InDxsXoLKBaqDdYG
    TOKEN_ENC_KEY: AgBYozqYuKHrZ8Klic35WOsnnFxWp8b4+BD5lOa6kO4m1n5esjkLQ746yBEDuMqwZDQsbzfELGqbUb44gOc2l8CGkkemYSUeiU+7I1aRDgTaeh0v3MA6LMxPdxeNstsD/yDX3dStHEZ5R3ndmAv0euYzJf4EjJAw7Q54MnzmA9vfAghXyaB7RpdkUk+JMUtoTFJXdf4WA9qVOG5bNcviyeWv4S7rBYcL6W0hBZdTNs/A/ZkDJuPDdZtY/l51b5mJDy0rlLcbCAeD7jrFHh4H4qBbOWFNsbIJNTxxmGxhKVVif9QhWSG+tvewMBXhxZmgEpZHglytO0Vkw2vhL36rZqDu1yuhrswETV6Tk8I1UM+WEf6I1E2t0ePOnd7n54zGip7fjdnag66pYvcfO/4Hez45ufcrZ7GdnagHNWmwDYc7JQllrmXheANl3MT33sT8JKCdKlPQB7lcYNeVz3ebeSTzGWQqvpsuDm8igjd/ncceFCJC+rD8nswkfM46O7JBXKVdRwbtkQLcwhOSsijWjWDxQzl+BT82XNoa5bIXrGcI0kWFJNxgM4ybOpbW/hrmY9jrkeqmNYNKOIDAnxK1euGIeE1y6cxi4zzAzuyLhOjvapegTDDGiZ3w8CI1rHNo4HmbMeoDrfqKk1sWLPcTNG73CRF2CpXrscf3jLGeQmlxOibm3cwd9AOpXFHI8Aqb3fCgKvFqeZ+a0o7V6Wx5T5q7E4dmIC8FLgtN0FI6mOcbtfE18k+odcgaeddXmrUUk8UZj+ROhOHS2KMCgYzJR6Yl
  template:
    metadata:
      name: nutritrace-secrets
      namespace: app-nutritrace
    type: Opaque
