---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nutritrace-ai-secrets
  namespace: app-nutritrace
spec:
  encryptedData:
    AI_API_KEY: AgBX+0Y1tcj4f0OIyqPXArRThL+h+sWs6/4i+Rg16Gs9ZoI0v9FaxBMhyscXG2XOriV8fnNwWFW2eVT0xldPtntfGkNybvbo9wzZKoGoEgtBKE/U8MIQouxqdfvXFlWo/bjaX2eN1qEi1mG+mCOxzKHvnGgIHkv4JTAAj0l9FIEnmZD8D9NEYmz1D33vyqf59TUBGTAp6xkcPvWM4csvs9//w2gucVmBzahCK1BvPCVL6C4jz01K7EVk0/YM/mnaJplK2TBnbS1+e/T2vz5UPYntJF5uy3h5pD6Bcz7uUMgle+YccAnL0ER5OyTfBhsaMOBbj/J15pXW1f96564sXuIoWEd6l1Aji0AjXgL1VN/UxkCEH5PDLRcKo2Sp9TSbXA20KIFLEnGxHqsjJhJNBzdkED9z9wdfbM4vaQdOaGfAD1rhzA1NlyUc6cUWw1OnWvSoKIYEwWBWvGX9vXTcBuGtZg3MhVMoRTh/aWFuBq8PLSaSnmwdolkKnuMywSjCyFfnFz6RlNqH08gpXFjgwo2V7TSjuXP9DpU1Zp3gDSn6veiBfKpLKf3S+lZ3ORGoQVmvPZYRQ1ODMDsi17xO6aCLjdZ2d6tH0o1lkQ5DK4Qpse3r6Xxy/CALyvEdv5j473zB94qbQW7XPdzGrqgr9+qABYFrMOBndDtp/wSj8fcWh3joKIzfoEqcVq63lw3n8b1zj9OijQGIR9iFjTXkY78+XSP1JvoWkRnjmFl2oOV8J0fkZpVr5kBTYDJ0MEo3lA95KFYPPmH2mTFPMCT/aJCqIHQUC5UYMxte
  template:
    metadata:
      name: nutritrace-ai-secrets
      namespace: app-nutritrace
    type: Opaque
