---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nutritrace-oidc-secrets
  namespace: app-nutritrace
spec:
  encryptedData:
    client-secret: AgAleF/O9EsqdDfkhNePbaQnUR6B2MswZcr8AbUHgFjjylUzutSeGmFX+++DSWuXq2TKY/k6JNQP7uvY1YM+xTQHMuQAqi21Ra8WvZdh32aNoTm9/6bmv03gk3HPHodtja3zhaQWRdIQDUmEK7RE8MIbfBfF2tUMx1xUSrClxAqJlHegbrt3IWKM3Iin10Y2FGcNUIxvfqb2PkSfa6KEBl7OB1KhVf2h7TUspQKUcKadLYGSwagFZFtALmTBtCd6ZDEgca9o+avnjkkc64Soh/8B2OYHYlycFWjyj0Zgv5bDvPgGqofwPJiE7KiuzKZpgUHMmpYjgbDHwEZvthGaxL4GoDSQejYFzRPxNLOarOOoxByZslpco+xYWiIkydptNOe/GTaBjXXZH56vUm76Qfj2FHzp+E2os6BYHdWfOFuflaThjEfr16wY3nTaqAdaqukalOL9yp1OKLqxsvQ+tFwKnIaEpyTC+UT99jBitmv+hTGVfXObLxUeB7hVKdftkXe2FuXtHD8/9njn5d2z2YZLC1xLaBICQfcy/8kmLY4WhNvQYvd/ir7odBD3qd3nSjx1Dg/wuyyHvOlhVmmGyg03BtAmoz8jdT1xNv37NHC8CnCduNV2/MDRLnPMrlgKAvnTUd/xQyuZIpL3vvhhPH7lESv42v4b21wRFJ55dsaEEcFmq/G23BQopgjIcLEavWxhnMLZIWbz9F1fnXRXc4QM6zU6fCVlv0co+RsPLnnBK46ESApphsZBaZfCxFLhzbk3An/CpU8u3NDfeCCypnWwOtHgPzZFLco=
  template:
    metadata:
      name: nutritrace-oidc-secrets
      namespace: app-nutritrace
    type: Opaque
