apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-bottricks-secrets.yaml

configMapGenerator:
  - name: bottricks-config
    namespace: app-matrix
    files:
      - bottricks-registration.yml=config/bottricks-registration.yml
