---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bottricks-secrets
  namespace: app-matrix
spec:
  encryptedData:
    as-token: AgANSXfbvJB3PiwT3PB0L4uloVw3lxVjD/uDVjWmLTtprQuXMEfGt+pcjwfqH5H6WjWtLX16PA61D50bmo2m4ZuoLNCV3gMGbmW5FpCFzfgDj2G1Ai7YWyjLtWkIUxFHZyfa6g8BNChD6t9owJkoth3ZaDsSSBivNsajfWUOk7isvYEc0h2ebeQNqn83OVQuWepnwCn1Ee5Tq1K3Eom+pnNbNgS2eA5oF8YWP8nwtojSlun6LmD89NVBcFAh6HPuD6698ghWqaUzuR21I6fvIR7G0GHaI5IWdEQEL+69WT+kSQzxBcXn6gduRls9y+Si1Bk0STDy4NzyRipsX6b4zkmg+RftT5h+xKQR6ffRuWc1nwLCriUwj70qZJVBBqq3mohAS4PWM+JohoJ4QwxrfAwEOndbgYsOM5Q2sNlDKS3oNj9UxC80bwr/cY6x84ivbuYOfzh1VesIxCUnEHAaH3MNru04qlEdVBsIGWVTcMHFqnYwWcZpCI7jKUaHCpVGipNBGJGbW46das2+anvHzoXxU3AaA7gkuTNiNr2ydg4jAp5qISqSOxUvZ12OO/mI3jYGsl84QqZloLVpIUDdb9lSedhrIoKRoO8LIaXMmnfmrSUDF1r6ixLOkuQZhq70+cTt6BLW2Q/pZbL7oiGOAUoZ2RjYQKZrV+XcKEmyDAXol0Xvd6qNMXutPdT/N+h13IScA1I1CQtyVvc8P7jvkHS7tMA6FA9V1cuiz/ddArSjjTzHX+tGMu0stTy5/FqsNDMOFiw6e9GNNY3tF+tNiAEO
    hs-token: AgCOjxOI4VkyVQB7hdNzOtvIxAr+hghploty/SH+V0p6zE5kxzIh6GqDMsqVrsjBsSCvarDh/DHtrY2ALw7K9ia572+oSKrcmwlfp12MUs7D4qJTRSv1waD0htzWHtu+uNNmfDbIM8UObQWQiX9dINHhDKXnQ7lNaERZ9Ey1mAWpCzyDJbXkAGIN6CCL/iS2YGS6ZDbuMtiapyPKeaWbuOEEng2L7El9ik3k1+vKB98xo5MfHQHIKdLUHJOe3hx6P9ZrEjc51BG9P8D5I7PTXpWQ0BJU8rAFlKkKCweUBTGWaxVqDeTAT7mj1nD2wJTgHrnE06W1Dl6tfn484a7rzd5N5bdHYDnXnPU2hNVcuB4/MjbFqC3HAZNrQ4s7tmUniwxgDEtrt7TJWbMMV39hMdgOL3elWyyCF1/QqE9obM/bKO53u6oABDv4TTtrxw2MBTWMlkyGaUUU2o9oUYySIHJSeqX6zDBQtz56QLmLIIBcWJ/ePTT0p8IeRpSgl8YmTkp3QxIVQaVTnkk94fqBKiU5US/DM3RJ8q6ESuMGv9cKzxTnqsE7Fg2cuVYqtu3USNNHutj0ls+X0UYMU5cdzAcJYThDwR7G93Q0p0Fdj2vnmJ7DNT0Tovz8DqccXHIwVC084TZGd6RLuSZZAzL47LkkR64iSePCdPUupPuvyHF9FUob3hOm8nX/gAOo/wwNR245oPmKrat3/7RMHy9r/hjI4jez0rtoZiX5fR1OSO+iX1VlfJU+N7dWBpVF7S7uA+bm+8COAArKGBw7zAa03jt8
  template:
    metadata:
      name: bottricks-secrets
      namespace: app-matrix
    type: Opaque
