apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: location-borooka
  namespace: app-dawarich
subjects:
  - name: dawarich
    spec:
      fqdn: location.borooka.ee
      protocol: http
      target: http://traefik.traefik-system.svc:8000
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel-borooka
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dawarich-public
  namespace: app-dawarich
spec:
  entryPoints:
    - tunnel
  routes:
    - match: Host(`location.borooka.ee`)
      kind: Rule
      services:
        - name: dawarich
          port: http
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-dawarich
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
