apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets
  - cnpg.yaml
  - redis.yaml
  - chart.yaml
  - ingress.yaml

configMapGenerator:
  - name: peertube-config
    namespace: app-peertube
    envs:
      - config/peertube.env

configurations:
  - kustomizeconfig/helmrelease-configmap-name.yaml
