apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets
  - cnpg.yaml
  - redis.yaml
  - peertube.yaml
  - webfinger-nginx.yaml
  - ingress.yaml

configMapGenerator:
  - name: peertube-config
    namespace: app-peertube
    files:
      - config/production.yaml
  - name: webfinger-nginx-config
    namespace: app-peertube
    files:
      - nginx.conf=config/nginx.conf
