---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: posterizarr-jellyfin-api-key
  namespace: app-servarr
spec:
  encryptedData:
    api-key: AgAFzolwcCzt/HChqH1mdLaPeeTLNJNMwGdQuGZpN6cvUr97iSPeLlpq5Q0ZCc4j9V5IIhvC0fAB7RcxspwXLVG9igI6OykkWoSqj7oyb0Ty2LNBBbM4z6Ry9rM9V76o5WyjrbizRIS1RAiFruWpOGZTYc8dj9wwqBnyhrxtjke6dTEinzBb4ao82BF5hA3FqJxHq2lZzUD/ovZ9Eig0CLDiTfZcD+Pa4m7TbnTCmU9zGk386PvZu+/LwllNoGpcf4JsI/CLGlfG1wL62iep/FGKjJ7deznLEepGjDyDoqCdZsj/HL5YOz9Rt22ubaQgrw5nGIAS0MH8jMcyuaAM7xargaWy7UQOHlTImFubX77NWhNPR+qVkCOIbv6czwpsM7SaOCzmYCvGfTJi+MpXRraSHF4wLD47B8H22fVEZ5RxbzpQVM1Hmmg5mlvd0Jm+xN7zqLiz8NBEUpfZUTgDDpehYRGyU5kwlRiF/pyKpL70UW5BaIiRA3spb54LGq8/2xrF4HJqarf6kwYaGmiyf7BkRSBoK6BccOAtsUt//ADruRhA7Hagu+JkJdkgjlL3Sn5xVMQBP8ELK9joZe35o5t9UUp6EHFSRepcSBfI9BWqaNiBQZ6EsmXzTFZo2debFcKMaZiAg5R/HVV2J7NsoemyR8d6YNdvNP4CrxbSeFsXEUDhkYM/n8MN7sfwFjJe+2dGKiCeLPMBHT4oEij0lQjEDGLuBuikFlsJcLtPX+Smog==
  template:
    metadata:
      name: posterizarr-jellyfin-api-key
      namespace: app-servarr
    type: Opaque
