apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: anytype-heart-decentm
  namespace: app-anytype
subjects:
  - name: anytype-heart-server
    spec:
      fqdn: anytype.decentm.com
      protocol: http
      target: http://traefik.traefik-system.svc:8000
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel-decentm
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: app-anytype
spec:
  forwardAuth:
    address: http://authelia.app-authelia.svc:9091/api/authz/forward-auth?authelia_url=https://auth.cluster.arpa
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: anytype-heart
  namespace: app-anytype
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`anytype.decentm.com`)
      kind: Rule
      middlewares:
        - name: authelia-forwardauth
          namespace: app-anytype
      services:
        - name: anytype-heart-server
          port: http
  tls:
    secretName: anytype-heart-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anytype-heart-tls
  namespace: app-anytype
spec:
  secretName: anytype-heart-tls
  duration: 672h # 28d
  renewBefore: 168h # 7d
  issuerRef:
    name: custom-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: "anytype.decentm.com"
  dnsNames:
    - "anytype.decentm.com"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller
  namespace: app-anytype
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-system
