---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: integrations-synapse-admin-secrets
  namespace: app-matrix
spec:
  encryptedData:
    admin-access-token: AgAmFhJgYG5gPGPyxqAnLBvx5vg8TbbsKcMTHqm3z1vus6QBa6NIWdIqDMhLoXsd8syfrOHfZpWLBAvgUUYONZu+ZIlwZCWOe4coCpEkeyA69eYkm8y18o6hGgE4RmfX+gu7Bz6jFzLPevVXvizwz3sSW4znKP4VhcJNl1LPf9QA+lxNYfXBXAS+AI00NsUh2yG+v+xYDzXugcJrE1hOWeRLT2MRbbPv7HsjidLPAzU9bWdtHnR3lx3de/u8nBuUzbB1C/AgzcO1TeXocNIclzpmjoA0RdQH5GPnhoDqN4h5fyJZyzvAbABawBhTGvhOJkeR4MW2dyMSuBxgrLlBPK9piiji7rvfU0pBcqIDXSTLt/wG8TWK45SqzqD8x8K87TUpfm03d6AeU1EDn/SgXQ3fR43NTCCx1Vva0TCBUc73+4nKK2a8Qtd7xnjgniebJk9X/MppacHv1ozt3IGMKioC0zgvm8/cmPk/+smz+QKvs02uguGp66CD9Yp36e9Bwl7+X0LKJw9s6gJHzI5WEgQIPDjW0iyO0xU+/xLxl/ynXtNCdqZ0zSTKZujmg8rQIFlJJPKQDn325XyQcPGRe82mf6ZIv30GIolmzQocrEVrdP2K8zGTKCBC91Im88d5SsxbMEac8sRiMs7YUdwTjdME0n4aP7m76GxjCTDCVb5BORLZ4CUxgHFzy8cN7o1qNH+eA8Z7Sk5Y8qI+P9O9bsPJY7KAfef0Uly29JCFSnkwTKymDTIn6iLYmiE=
  template:
    metadata:
      name: integrations-synapse-admin-secrets
      namespace: app-matrix
    type: Opaque
