---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: integrations-synapse-signing-key
  namespace: app-matrix
spec:
  encryptedData:
    signing.key: AgCF95jJivSu5hryLfMQ8O/kFY5i87v2Aa5xu/o0ecx4osanK1ajVI8aISuWqi/j5oDWlq0ckGKro+XDs1WyCBleI+iMNk8PeiPEwWUl9AfjjQlBccN4m/K6xZdDqumlOfgKw9QT6nA42d5Bil+jEdR3jaHUKUb+Gj+F4EZbmaVd+AY5yYf5r5bn2TV4O6nkSbnBlj75lwXK9Ihd/ApCUftsQpzLN1dwDe7kMCpC8LlfgsYFesMZHlxx4tH4S5aiWqzQSbIYS7c1Knfj5459RB9tVW1hJX5KGGIgMnk4h1g0kD/sVmTekFGBC0X5QhUHXFsC8XyF6oDBlPR4ggZBnSd4zdysmiSM5HUMEsAdiHole3xX9egfyO05jZlkMAOKT0Tl9Most87G7ALIlK6NDFrSc0FKrSzqE0mZXaiYoh2DtGToz43AiUF7dtBQxCof5ZZgzqlFr2rN1VxrhTKXppoKyD98lzV/PMPwAMOzbcIQslNURcrhen0K3sZH9zw645EILt5aXky88sUVrFUcrIi2zi2dWuxMZeqnS66yq1jsRSujXj2wggu736hdit9MPT/GptXMWG949pvtJYLszKB9n9SwaSzNL1AbXBlazNGR98AupQf0LfQdPyrJLFPPaqsvwVutYZXu7kaNwaZkkn0q2SlHroDHGEG4x+3pZvTxHm3tjKVA6v2TXFN8n4bqhvZjrFx7CWrzY4QyX+/gL0rFuD+X79N8ZkanhlSq9GDIwLHWjX8L/1k0MGm66M1845DbZY37o6xn2zUZ
  template:
    metadata:
      name: integrations-synapse-signing-key
      namespace: app-matrix
    type: Opaque
