---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich-oidc-secrets
  namespace: app-dawarich
spec:
  encryptedData:
    client-secret: AgCRuv6RvKnCyqLHj/aM3/7wJAYy1+mX7ezBto4hNK2X7kL8Ceitb31I+HR2FuDv9BUtk3PA2LUvNIaT4gnKrV0tRELHNffUUXyOvAFQUZ7kUVGMSaCr2fnUsz8Ui7o01v7QNsjPxU4XTjt+N06YleVFGQx3C/kYNZz+aSVyunAM3GRVqJJ/i3Zryh0H6xsLKhXhnBNBrJwfQTRsADindxJCCAGCT5aFikSZFpLxRp5nKFidNLj3erLv/V8qmrwy3Jwg/Dp/KJCglUMYAwvAUPnfTL7QNa9HAqU7MTjP4kYCBBBXneidRVQ6Sa9m9XvkpGDp1nV6CPbEjpEUJDzoprfvd7Bdpw5ongXGRdWaU9KPh7ET/aPB7/jaXmJkV5jkSXbf0+No3zlq/61RAKrRhQBvnrviQKoaBY/4fhiX4yF8lG4KLrygeQbNnZQxvNFT9f9h0nrIUjcXdrk8QLDSXU5+CVzvFt6M+4J3N58Qz4Vm2SBT4uiqeTdwMtAffAzXjtyMp8VFTAoRdqfoUxVevtRw87oppWdECor6DGdJYA6KuI0yzXK+85ONoqdf2N4lXEL7sre+LSU+r9cf6D4H2+UZ5bfLbtD/3iEfawDck95av+clWizQ61Ew+nOIS1zmqdSxvtTgVk+BRIE+ibCgpupXZ9FbdOU6oSKdlMKM6xGzE5gVY34QHIfzL60ONV7PvdfIwfuhu+QAaAdG1AnNfh7R8/sDGyM4ELudUcbG63I7C8QoSs8XrB3cv2X3yq8yMVKTI+EMtAgGroYQQVr7W1oYmmfF7iB73ls=
  template:
    metadata:
      name: dawarich-oidc-secrets
      namespace: app-dawarich
    type: Opaque
