---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich-secrets
  namespace: app-dawarich
spec:
  encryptedData:
    SECRET_KEY_BASE: AgC6klzk4DYS4PvjLkS6Wjk3oJmNWNy0P/R5yMZYNssj1Vwt6xFfbLm7Uivk5yNHpwj6N/j5ik/yhGBpWDNcnJgFXORsoNSc57lnHAm8WwtPwUoDmJMzft1wCWzfpw+adm5zLE3Lmp5KGqf0xBBwCqmi6QkYMfNXIb0gtiP8jdx0469OSuAzXR2T/aNxTGsqUaRdXupXhnL3tN6FZrOwQRKs4nqBiKXtNnJNRJ+LwSR/O3q9MFyOb+af3DwcetCMOq6W0ViD7BYAbBzOXRaxXx4dIP78e6x8amqB56YGTx7Q4dvPWCjHpQ/l6zrzvqbdpY4twregEiOB2Vimpc2toRHK5mTNUZ9rQUL8N2Y6TsmSyjAJaXFfBxAbgWJTf/vrokVyjGodjr790Zg2CpsmGEdGJcvm+SSQEUSGQB0tQxn1nhQcdm4gTRzmq9lPfYXNonu9DbKPVnjWNZVTYEymehrXMisRxnLFguRF5wEa2qfrgmbGDSpMqXvvtp3+fva8/jYcXGP3kKxKaVwDZH2SPpksNWkmwfKoDZK0McJKCstVDvQl9zYPmrKz54URh+e5ef3p4BHlUFMzOGIKRK5yyyNlGk2UgqRPIU7tKITXg+wDP34F0DKL/lhiRCUoC+4WuhirIrGsOUp5tRY2lVTeQdvlzcsq4GNmLpMak6+aE9BIG1EMM2MM6u2EEBc47KytjgrrF4dTByXzuvW/pQcA9cIQ0wrijh9nJmE9b+X+CSqBu3XHiu8fI+ODvrR6EvRwlWguw1fOnAsjmjcHLRgoTHbBwMJvvFsJQRTecnsOnHR3nkUeimVv19Nib7IAeamQOnyvUUM43LaPtL2sg0hyrgDGOw+KWEBfTxpOJ5V+ZlrJqA==
  template:
    metadata:
      name: dawarich-secrets
      namespace: app-dawarich
    type: Opaque
