apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-authelia
resources:
  - sealed-secrets.yaml
  - sealed-smtp-secrets.yaml
  - sealed-secrets-client-jellyfin.yaml
  - sealed-secrets-client-mas.yaml
  - sealed-secrets-client-photoprism.yaml
  - sealed-secrets-client-paperless-ngx.yaml
  - sealed-secrets-client-peertube.yaml
