---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-dawarich
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgAWnWYgf9ueEi64YslhJ7uS21S2NPYOMZcU1+HQD82s5DmKDr5TnzORxVOgvlRYPC/ooI4g9XckJb5gvTG77xngtFaSIaTQfj3AL6LoJ++rT0qPYNCV9UDJu6dl1PXwr0aSMa4NSXz0GP/tI7HRWgdrFLnLYyX9ffdu4BzfatqPAi7jVwNwsL0S4BLiOs1NA78AkLYCu7qTS3PFKtfKHlfYWts6iMEKjbXej60cnYThtv6o2YIurmd8zP+rcg8tHiU755BDjpIs4BbPb+pegF8GsKE6kH7ZTHX45TmsazL0m3/KdzAFQ1oTawnWxqbub295rAeHuP6hMil8P30XptQ/W6kcVKX700uIt5NzUDzphO8hgQ6NYvJfh266trtFVY8LpSvhc1SvuA30laBAYHTlDtYhOmqqrrcQbMLZ8f59q9etT9BSdIrwFu1q94taqN33LFZPvsPX9JmLsc9XLwsH+hWN2p7wNB6UELfud7Kkgfp4xeKIJSuqWfRiNExvIdfO9q150X24v7ch5+623jZGjiSiuZgQRMy+RtjqOxWudZfhnrfCl3UoBQCZHShxzLVOe+vyZjT9LbfBe8gmAxFFQX+VG8oBIp3hYUe/4iPStq8Dqbd5D5EtSVYpHSuG/XrYXgd4kOn3nP7OrJQ47UScdrTZDMIPUj4HCHXJ5wo1rwW4A56VOlhwRs4Y7sjwAMNzpBAx9D67PZ5Hir8Z5SMR+nc6JpJTLSZHHMcLgFlVHSJ6JytLD4ZavfdiGwXNbNDGC13G9YPFqIRKzLEMmeMKQnzvOwlKZyI275NoXYmB6sNSbqAPGcuAwtBwwpiIg1EcNZFoQGFDonmPuay9W0RUSH9uCBTGpqDFZFnBx53nobDU2A==
  template:
    metadata:
      name: authelia-client-dawarich
      namespace: app-authelia
    type: Opaque
