---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-paperless-ngx
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgCIYM2DAYL9JfPEapIGhF+m998Csd2V29fmD1BeRJ7i6C1C2Z0nW5WjqtIzn0vm5C2HmxvAMTcAGBujcZwuPI3oMtskm9zvKK68jdwlmAVqq2CGMWWn7w0aqGxYkvKjLpd0YMaAK5T66uwevFg46myEl8HdnshPFEX0y6I5w+2XPZuBjdvDp+wH1JNjf/1faJ6yTtbdz1KX2G0UUhmFaP3kZvoXEkQyfz/sUFOiUhCS68eYpxs2cr/Liajx/v+idy1WxJmaAbdkjBFLA073ZdIkzRq83wwoFRmTmZeG8jePemJBgfvSy+zczG1XZRqRF63izBPVlfo0kOJvtfhp6jKOW1kXYzzAkbVkpUS58CfJ4PK8dbwMbZtQbqcIza+CaZ+hKZkGCGNagdHzcMxeW71jdWCfeNmy9kXA4xIPNiRX0MjYXWBvYFSBElVMjP7yawQTjM3PGCr2ejq6SYyoRCRc1UkI5tFxU1Zi2q4k41Y2oRZ0DYg/aJ9MWQ0zKk5E4zV2PzwnihgPavKTKiZhTkYuAa1RGlxpOXciVZTJ52T3ax/HlZFi9r84qEuic2BhmuicTHaQDZzU4s2zhIR0pKar4C4IXbzhpiwLdTECJ5A8AyMt171T9MNHfTS8AqPWxvCvL79kS2yTgOXvTQu61fwzCqi/MjDqDaifvkGWx6jO0eIstZy3A+PEL769W3xBX5k/svZS81Wa54dOPAYcv1hqT6i7bmoIkxyksol9v2/r19U29SR7SpnO89Q1yoGodrtwwnYX1txsQNYKHrM+3DfEV15VHu8q18eEUElf1/sSZSPtM85AqkWtfQ8Ae0P2uKxy528wD5r31xEZGufIZOvlZRtyuDv+k5j2VFoAFF3P7W2JTg==
  template:
    metadata:
      name: authelia-client-paperless-ngx
      namespace: app-authelia
    type: Opaque
