---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-photoprism
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgA0sMfoR37XB/6sDdDgU+C8ze/oYeXwx2NRvorrg4c1Gey1NOvT+uwrXYL0HnjE8A2gmDbFlmQqEgmTvHSDaE9OuPbu2bodvip1uFT5R63nb4O5k6wq0dH6FVQGLPOMG9pcmY5ttCP4MU5oR/LQ4fi0idpflF2dmaF5DyaWOn017YVZhTrTe8JcmH5qkNAothLbr92rRbDtZwDt8hlB7Q9iCayCl5qQGdxIpIcqN01t34jaXuFSMms9KL20B2cOOgnnckym7+EqGJZFi3QgrSUqDuO8wBPRh2LDhZ9vFeKn53Phucdu7C5lPUKS7LHqKAGnGJLMd4IIrGR9dF6f2ZqUG78tZCZ59oCYVoylSxPUuqlU9bMQ9Vuoe7V0fLkHUG7gVoFD070BonAV3YgHdPfcZedLWVJBgbEJlZnQAAxQ7+1zLO7KGyTF6Q84rsc7VKtxzznMBts6dIDaAdRwzm9pp7xDNIoIw08TYQeYQN1XmD+aTOiOrXWxjXRYKsqyarIZeB6z4BUFnbDzj0pSbMc0zoNiq6rX+yWb7t7X82Vt/GY5kZYzQ3qumVRKT4OnBZf+HIlNskGm2n00+HfGMxii5VBYe9zO7Ye5Cc7J/Pory3+iJckGF4cwDEy6jQIUAPn2eniTLQxVOiIoeZAJTBP4sippaV/CykA4VC+o1xIs17KlzvzsKCHP1Bjfi7Uriojt9XllLf2/K6dCBJsrb6zVdYxP/N+mZfoc/IrjnB6tSwZhnIxXpw3WEQzrn6vdd9SNBgl0eiMV72OL5xkF7kuXAoiK4koG10T3vjoP4uaX4AbU1fk440DJHfzMf4jpwYWJXfceZFDnUDZ2QbZ9zpJglt4ZtBX/XSNLx4N5Bv8Z9MDGpQ==
  template:
    metadata:
      name: authelia-client-photoprism
      namespace: app-authelia
    type: Opaque
