---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-nutritrace
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgAh1mM/dBIujF/lftujMH+f6Xxu+yjtnDrVt5UP8fimUtp5ZhA1rDOcBlOzEcgtYXE6GZOVW6H6W9DBNSUbuZVkW8xoeKTrk8xlk/OzsQL/0WeBA0ith8GCBpY5hWo0WLJORNGRmz6PAHcO81/olAsMN2DLF/sA5CpIbxeDWQqzzvXbx/SryZfo+3AB+AHypLEJcfYn56xZwIVRoayW0NKEzVyAP2eYwMUF038ukmHGo282t5C+vSVIiedhOAX+CgrvgTajgLYMqquJhKrDcvU78IbzBM5Q8QPeruH1GzeBlNqnSAUYNCmWKDJVmAaoHciy78enYg18r+Q7VSa001xB6Onm1jRTqqyvbTLcklgiw4pwby90t/rQkkkIefv8gtpUsyz17XBda0hhubZ4AA3gobSbBfkUZ4Qt//8KB9lLEcXalpcpMaVjfMip+oSbDCPTIPsOcjyQv72SirGTQ1PcW7ulAS+ibZ9YDiBPuvac0dpgGEcPevN9U0sZdvivxEgkcuyAI0MB87GfRZFaTJzFUwjDJA4ESCRJyUW9M+qMpyQO3Op04c/x7nFeXtZGaMujtmDj8bAUvDNguMZPPyp7f5kMP77M0PkRuPL6Zli48FkS5bbjkYhmB1Lb36fnSImDTfnkttSt9c+kLBCQaqOvsRqmjD0Qt8muRN0MUoS6uudizKsNvITSjP1V4NBaO5zqMY3BEQFVXZSb2VUKxnZ530E/9fMM7yMuWc1gFaMeg+pcOimUFebpITuyyBj9EIRsKo3zs5rI+feWNOMnrNbV9gKN7DoriHNOSAqvwSPEcm4jrRADELH93PPNUkGeowtDAPemmCYPHOlu5GRAZZqlDGTdG7op7A6z3V3f1WIpylFEAg==
  template:
    metadata:
      name: authelia-client-nutritrace
      namespace: app-authelia
    type: Opaque
