---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-peertube
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgBELsIvx+XvfWP2YRVahtAFseAoSIAOCJwywUTtFNypTuFGF71H1vhtvx4dRVnhtxCFgDF83df1m5gxHhfJBgJ6FdnX2Sg0eMJV+qdt2taHb8qRDpN8ArMxKTKV6mrMWlBpXxWWm1vvPtX2ypZwclSxRSzUHjPKNsvxQfit0YTXHsHONmuiaf64Ev0o4GXvX9w7fJYA/DOWMP+R2nnP5VaKXnfpsw5c+DeovYmwyPLV7tPqPDO6c0jvaIMDnKRKZ0m5k6HpTpcpTq73/CiaSQCeeh+dFEeZQ+izBdtbwd9MuZ0WMY8Er1lPmb4SlDyy3h0f/I1oYZLS1Zg7eC/6qEjJYstjhNLfsGyDo1iHNNJep7iTbE0D1f74mpDitd+04BfbhSsK7VxymyFUT9UKZX12RYeCqbTvExZUMgUYGxd6edlNodjUaPoxMz+UTZBpJUw8yoesGQEAFzQYPWIRKhNXObBpYGKzFXsGXY81Az9i93pUtCMG6JTA8inhbUZmiyIAfAHwShI8CfE/s8dVSzl1imD3vHiFUChevEM9RdZ/g/1CI1eNFXyeKJkTjnXUj7zPZ7PgPaCVYv+ATsKdsjzr2w9VpP4HqiutgPNEfMdoKQ9TRqLU3+BQRZRSBK0SZ1kE62gNtAABOTLOQc3Jh+HOh7Ok+BnpElG9IW5r9BkmTdtG+SXn47bKHoRP/90D29v+b/6A9dMo9AFpYHA6JrlSsIMAUA85OMslH+KiPmJBdzpXpvR5oBwW06xnfkgoW8t6a/pKGJOwpnE2V8FeKAfqOinMpcyNu3Zd9ZSttruhiKRrrj++4JZCEVIx35vTxPxS8BOovD+1QXD/ZTs0AoPkCSRVHsKjv54DKqLZsvwDNh4Hjg==
  template:
    metadata:
      name: authelia-client-peertube
      namespace: app-authelia
    type: Opaque
