---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-peertube
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgA68+vabXWFRSpv8KZqVhFYQ/up8KFPNjnkYlj2rnrgnE1zOFBqI6SzCfKuncmQCJ87J5vgDJeB7ISBoqc7wREYR4t2l5wUi/uITyC3zXusIX57nDEyDmNVTc/hW2Jh5cTKR+5PSqN8lB6oE24ti9ywqQay10Pv7cvWjnJr0o9N1X3CyGKtaOhtbX6hQDI1r6UByDr+u07AgQPbM0P7x7HDgqiDc8V2b8+XrejBseUxjWvijbR5KtbKfwLqWKQWcn+RPwJ8IiRBpx1J+E61wC24gEvDRnNa+hN4uNJMbV7F9C8m1IgS9wspoL2tKFH63CuDC03dPmC1l768X12ah0GeHpDrjjSUfuRIX44/c1dlurPyvZTqEF7/BrTuNqq06kPGckW0G4ZjppmUrjQ8v7cZjMKd3RxvTaKLgG3OyOth1ScFOZ9cdgLWy0Y4DyyAdzrux1NqDdGCSYh6TOSOpTVII5QXYUoZxwh7ngFUWeaImO7i/lK/5lT86oo7PA026suct2kbOS0Zp16+Lh9m+1qEohcDFjvwXHsnIK3FGiS+qw3Tv2fdkEFan+Y2TNtigE+7rBlGAmX9kGi5fAWt3Jp88mlprLamidDg/Hsptfz6ZXixAEAbH0tolZk30SKt2Ah5Bs0b2sZV/VsQX6cUxYFBSOvaQJW653HtT2Ff8U0vg+qdZ2csDXOP4IxVaHkQfWzT7TIBWRC2ey0HliVYuGuKzZzf0P+gNTT16d9T+hTxNlFjrDM8ego3dR10KD6HFEHASGL65R/WNcxvllGmkgDfanlqy2HjZAb8snVERn+nHrMB605kFPBogIaQlGV1SdsmPWp/FAeWeq19AxLjO7C4TqhqmCUAlYQRegt9QJDEIzKonw==
  template:
    metadata:
      name: authelia-client-peertube
      namespace: app-authelia
    type: Opaque
