---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-client-peertube
  namespace: app-authelia
spec:
  encryptedData:
    client-secret: AgCsxIBGT5WGujpB8diCbiwB2ba1w8F+p4/yc94fDf+ucHgJxbVEry8o3aD9Ic93IMShb5ntzibDBgI96UGc/KZ5x4aRk+xff7I8dM5OQWSpNUxWrEKmjKdxEfUglRl1Hy7nZLfX2RQtE59wAEgxXGjl8Ewh8wql5cwIly4WRrekmWu9y2qOLbk564INl9wedHHU84i+CMMG9ySmjvsEMxoLamzoYSaKNvHCS8fR2vK5COMP+g6/A0fBponGeN778FzLeADho+cVVmVSsTz1dx4Y2AauP7uMibo7e36+r8olsxdwjuZ/ezkOu0AV3rWUp+R/hfKzQ59gNlv0KzX9pSh5TscZHtHGtAR5GqTkUs95zJ7XI2ipcYlGAKVXDd7ddK6D3ctmJYQLBgq5RZmkRteEfry6Xe1NX2sn0wuBDwd9FymxlAAuem0rANDCPWz/OgUuLTaFsmdOXzKBUuc+co4nvjnKKYDLGC3ALSnKfdV9hBDQcapjeLzkrUocLTtWnbgSPupVkeiXEIfVW1W7G9qkiwRTj9jihnXghfesR4YcggpTunxRcSjkWl4cs8lT9gvr1xpafo/EEFBrnrjN5n7wQvPEVQvMqKWr3tMupQ6l5frBfxNPkNgQUzFQGykqjdwDoqi/T/3VZRkX6+jQO+hPJi853LbLolonCCfnxIcbVyoPvtNvgdEivNZsoqYwtnWSPkWNlZwr27csTNnsQwYTsZgem0N5/ZQRuMPWJgbo5sFFldDfodQWEUX7JhN/HJj6WzFh61gjS2jMyhZ800Kat+UFWmnVsAwqqw+I+Eyf67Q5RD5dnGVZ8ybHnmj3DiWIa5pr94qpIejnDY+XnRViRYHMMX51Pksely31XLDH+2Z9wA==
  template:
    metadata:
      name: authelia-client-peertube
      namespace: app-authelia
    type: Opaque
