base-url: "https://ntfy.decentm.com"
listen-http: ":8000"
cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "12h"
auth-file: "/var/lib/ntfy/auth.db"
auth-default-access: "deny-all"
enable-signup: false
enable-login: true
enable-reservations: false
behind-proxy: true
attachment-cache-dir: "/var/cache/ntfy/attachments"
attachment-total-size-limit: "5G"
attachment-file-size-limit: "15M"
attachment-expiry-duration: "3h"
web-push-public-key: ""
web-push-private-key: ""
upstream-base-url: "https://ntfy.sh"
log-level: "info"
