apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qbittorrent.yaml
configMapGenerator:
  - name: qbittorrent-config
    namespace: app-servarr
    envs:
      - config/qbittorrent.env
