apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-authelia
resources:
  - namespace.yaml
  - cnpg.yaml
  - chart.yaml
  - secrets
  - lldap
  - ingress.yaml

configMapGenerator:
  - name: authelia-oidc-clients
    options:
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/component: oidc-clients
    files:
      - config/clients.yaml
  - name: authelia-webauthn-experimental
    options:
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/component: webauthn-experimental
    files:
      - config/webauthn-experimental.yaml

configurations:
  - kustomizeconfig/helmrelease-configmap-name.yaml
