apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-integrations-bottricks-dev-secrets.yaml

configMapGenerator:
  - name: integrations-bottricks-dev-config
    namespace: app-matrix
    files:
      - bottricks-dev-registration.yaml=config/bottricks-dev-registration.yaml
