---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: integrations-bottricks-dev-secrets
  namespace: app-matrix
spec:
  encryptedData:
    as-token: AgBe79CFWUKBfWPCOBK0YrOzF3hlIOiNYCylzh270dyjFB97pKfWh9JCs+4O/BX+MNn+gnnIjKcoEvzTN3WvQBb70lMKGLVIOSYpb2DnH8oyuj9lJYqVdEvC5geQzTX8M0JA3r14QcntrvhDUiAcnhd5t2wK1Yd3agxiyBI7ivZBlR41jN63ymG941M86Rufl3yg/0SWSuIIdU9M4yxwWnjxriUJ4MD73AHGAEf+xiuP5ClEEmLeDENYlB59U8L5WaYignXoDzjb/eteODTvCVkn1/eSfRrqVfM0vL3gIlQnF0uKcxjKcb52MKjtPmvkgH1G92wBoE0cQNck/HLvEotL6XTCWrZTN6Ym2Z3eCxLdFVCd6Y0WU0VvfIEJWZ/SBRSuEJ0qLkRC3cZdu7aVOott0mNqlkxOfXuILIK3Txc/4T3tNWkzkPOO7f2D3FwRA6WzszFt5uD2j/FepVZezs+zxDF7Q3i4tJiAGMimBPdLbEkDw1ieJv6uoLBz1FjE/u5ErPs57436a4z5ktWtqVWMCPtnEGFDqeZY7HiogJaKN7ilO6kkXGA6zSivSfe+CcI/Z07r2q1/uDRf26JVwz3XTqOdQLFZvqVCLddZnir3Qmi7FtfG0+k7aTSXPN9jRKTbycer5EN0Rm+hB6ECAwYurbSBGm9ptjnJPT9b06SuuxBQEI1ZrhSai/LqQwdVKoaqE0zjRTaZ35PNfCQVE1FGul3odq0xOUv1CpWNkMP/nMm0HdgJepcBhE0VQvPAddMW7agX9UvEnPe6auUUz7fV
    hs-token: AgAA60ByLnTY/VqrmU/spPzVyPLQeos2kPQfK5A2zUJDTwPpMVp8Wx9tPn7RAsp21tr81po3x4VTfD9KGpmEehpanirGsmaYanxRSg8OLhVkzkoH62bkMPeYNKJXGRTM2rWZz3wjFKaBlF8MSms1ch2acA8Hm0a21SNF60OITHLJCK+MXjdgouMlKiFbUNte4h+HdpWeGDLUoU+e6kHFBiBD/bB/KNDiWlazdg3hu4jmNuFmx0NWEq87JYCvJUM+yVcLyAF2iLX88JwFY7+z3F+J/1Eg96xsfM9PJ/mp99NS269hgMMfuOmn07bKSb/cajXCluM8EohAUo8pMGPuidaPjOPhHPaDwYYnjAX7Ks1Ry2L10zZOitKn11p4ySA51tkFIKEYdjMQHiM/pyTBXbXDzKTqgpRkjXrp0Z+xWg7gth/K+T32pU5MA8LboNi86K9IfByNa0Py311T4tjMD1tcDrNlalY+KqQs0eLwAaxJ3MmH7U+mDNlAdqP6uqG8nEtes5qZmgk5dWz3i6168dnN5iBlHR3EFYnTcOtx15uQ6wzFyGH/JuWtgB3Fx/Fcok6uG5UDTBf+2Y6cquBR27W2rQwnkiX6XFo0K2RCeDitJma/je9kyVQsR8OtRuuwRpf+jY/eZeLnqFrmT5hOZPQ7Yn7fPgcYhcYKqUmHoZUY5YzX9dI4/H+PAoP7i4miK9tbGYVFJs0Hq55ywVBkQZ2tenLUnptBOHYVpY+Nhh+JRQIGe+e53T3EZo/uS6rd37my5q7fLbYJ7chi13mM1U4L
  template:
    metadata:
      name: integrations-bottricks-dev-secrets
      namespace: app-matrix
    type: Opaque
