name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v46.1.5
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
